### ISSUE TITLE
>_<

### ISSUE THREAD

**Issue by TDR-1000** [rddewan/App-License-Manager-WEB#6]
Hello good afternoon sir,
can I use this repo to learning?? and want to ask how to use it?

**Comment by rddewan** [comment]
Yes you can use it.


Thank You

Richard Dewan

________________________________
From: TDR-3000 ***@***.***>
Sent: Monday, August 15, 2022 12:59 PM
To: rddewan/App-License-Manager-WEB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rddewan/App-License-Manager-WEB] >_< (Issue #6)


Hello good afternoon sir,
can I use this repo to study? and want to ask how to use it?
